# Generated by Django 5.1.6 on 2025-03-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0002_imageupload_category_imageupload_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
