# Generated by Django 5.1.7 on 2025-03-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0003_alter_imageupload_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
